@startuml

class Solution41 {
    'methods
    +main(String[]) {static}
}

class NameSorter {
    'attributes
    -nameList: ArrayList<String>
    'methods
    +scanNames(String)
    +createNameListString(): StringBuilder
    +uploadListToFile(StringBuilder, String)
    -sortByLastName()
}

Solution41 -- NameSorter
@enduml